---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgC8wCxYp1U32X3p+hxyZ5Mpne4oUjrQcoSpH8AOCg/H3bFKr2+Yk0le7t+dKsLvFLwg+6xF1f4x0Qq8EGLBOGkAs1SZ+pCsUwwJ9Xmz8sAi0YKJnCJMCPCZAHcClnkLQl4l/UDkJUSZBJL76yT5quY2Da1XaYG2XuoFdPA1vKTvMKxxqkP3cdBW8bzaPPnXJFFuDhttWxfS4O6u+9riyWCeM8ZLOS+uA+iyg7nLqsDsfEznBMIRHlwryVVitw/0cBdfrY5nWms6lYbJVetXY4qCqqZHZHBhXSOclf9/JlHXFaXQ+iS30v9OLGz2TV0NnokcIg/C9uj8wNtLH+eSpwj5tH2UyIySKRLoegB87qno+o2sLroZrHoY25rcML2U/hahDwLz1PwXpw9L1cWGhL1ecFGqVjzUtHR3Iy6fKTj1To+FS6rtbfG7z2rnihW/Q8DG7wFWNgxM5dp8KjheQlmF5v6W0w9KvKVCrCpJkr2jcR56dOhNh0/qsFTXMRrhJHQ/N4ypsBQPo6JgfMAnAoE83xbgiLnR1Zk6aMAVO6GOOtBvhZQZJWPwZi9bs1E2b6W0wCsx/ZUGrYb7npP3aoWQ6UCfjD87mHRnVeoMVxD4pnyObeQOHIZj3XEai0SN5AcUjspnqP9gyPgVWXg4WyV6JKqYkALjlr0O8m+9aoufaj4p0MkxPdc6Af2RwDDa/7eYGFhlvSp68WpGf7L0Sw==
    username: AgBscPAWgKJ/wr9X6AR75dWgt+pSMS1vbjWMgn3u42vRq93dvIfA83MJf+tLQPl8QeokJrRUD0rzmavnzeP66j66q9z3rgeApLIBXE6vSqidDL8lbfzJR5iituIzDV8dkBzlkaRkJZ46Fe61Ahs1iSb6qx2Dg1vm1/Nd7GJGwN9vGnvbOdW8okK7FdFDVJ/sqj3dFwWJ7PgDKK3txgTjkM2S6037FGy+cAZM7bW+rBQqjzQMQ6g6+PjrIludMk/Fh8BOD1qFZlgFGAaZ/H+tt9kmM0j+x5PgyEyH14d8rQMEBfnKAE0okYj37hkxeT1T6UgcwCd/FP9SMEsqSoPnmSvmQISL4Sqq/djaQdr2Hr4SPfeFYDAWVy4T07RJsaA+wG5NciOQRyaXIURzExeEav+b7su83xRPAbaCRuUgPKxxM7dl/PE7H3662Xxqh0Eqo3yykJLn3HucCBCkNfcSPcTMGDr1hDPjqUian/J7Xgit0Ht1iOkFIFfaaLqXv/GB8doI+80kCEs0BYPvZfjUGiFQzUyUn5XzH+M+HBk0lw8cdTE6j9nB52pFolbNQefawJRCh8v+S9CeRKUu/m2ngvTGBnbyvZ44teiBXEU8PZ+jgA90PxM5Aw4d/19byis1TTtRE8L4CP9mE3AgG6JuCdqCZlMTCHVPZExXTUHIaMrMuNkvUWn7RMd+ZMP/UIIythuQ290eMg==
  template:
    metadata:
      name: db-secret
      namespace: default
